# Generated by Django 5.1.4 on 2025-01-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='date',
            new_name='date_joined',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='courses',
            new_name='field',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='study',
            new_name='language',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='time_study',
            field=models.TextField(blank=True, null=True),
        ),
    ]
