# Generated by Django 5.1.4 on 2025-01-01 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_category_course_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
