# Generated by Django 5.1.4 on 2025-01-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_remove_course_categories_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='date',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='study',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01T12:21:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='language',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='time_study',
            field=models.TextField(blank=True, null=True),
        ),
    ]
