# Generated by Django 5.1.4 on 2025-01-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_course_field_course_language_course_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='target',
        ),
        migrations.AlterField(
            model_name='course',
            name='field',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(max_length=255),
        ),
    ]
