# Generated by Django 5.1.4 on 2025-01-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_remove_course_target_alter_course_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='standard',
            field=models.CharField(default='Normal', max_length=255),
            preserve_default=False,
        ),
    ]
