# Generated by Django 5.1.4 on 2025-01-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_course_field_course_language_course_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='field',
        ),
        migrations.RemoveField(
            model_name='course',
            name='language',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='standard',
        ),
    ]
