# Generated by Django 5.1.4 on 2025-01-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_alter_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='id',
            new_name='user_id',
        ),
    ]
