# Generated by Django 5.1.4 on 2025-01-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_rename_id_userinfo_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_id',
            new_name='id',
        ),
    ]
