# Generated by Django 5.1.4 on 2025-01-07 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_course_field_course_language_course_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('videoId', models.CharField(max_length=255)),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='server.course')),
            ],
        ),
    ]
