name: Testing Group 4

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out code
      - name: Checkout code
        uses: actions/checkout@v3

      # Cài đặt Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Cài đặt phụ thuộc
      - name: Install dependencies
        run: npm install

      # Chạy kiểm thử
      - name: Run tests
        run: npm test -- --ci --coverage